export const PRESET_COLORS = [
    '#7996ce',
    '#E0555D',
    '#4BB34B',
    '#FFA000',
    '#8858c9',
    '#333333',
    '#007AFF',
    '#FF2D55',
];

export const PRESET_UI_COLORS = [
    '#ffffff',
    '#19191a',
    '#7996ce',
    '#E0555D',
    '#4BB34B',
    '#FFA000',
    '#8858c9',
];

export const DEFAULT_PRESET = {
    id: 'default',
    name: 'Default',
    author: '',
    accentColor: '#7996ce',
    bgOpacity: 0.85,
    bgBlur: 0,
    elementOpacity: 0.8,
    elementBlur: 12,
    uiColor: null,
    bgImage: null,
    customFont: null,
    customFontName: null,
    chatLayout: 'default',
    userBubbleColor: null,
    charBubbleColor: null,
    userQuoteColor: null,
    charQuoteColor: null,
    userTextColor: null,
    charTextColor: null,
    userItalicColor: null,
    charItalicColor: null,
    uiFontSize: 'system',
    uiLetterSpacing: 0,
    chatFontSize: 'system',
    chatLetterSpacing: 0,
    chatFont: null,
    chatFontName: null,
    uiFontMode: 'glaze',
    chatFontMode: 'ui',
    uiTextColor: null,
    uiTextGrayColor: null,
    borderWidth: 1,
    borderColor: null,
    borderOpacity: 0.1,
    noiseOpacity: 0.03,
    noiseIntensity: 0.8,
    bgNoiseOpacity: 0.03,
    bgNoiseIntensity: 0.4
};
